import { signIn, signOut, useSession } from "next-auth/react";
import Image from "next/image";
import { Poppins } from 'next/font/google'
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import { IconBrandFlutter, IconBrandSwift, IconBrandReact } from "@tabler/icons-react";
import BrandCard from "~/components/BrandCard/brandCard.component";

const poppins = Poppins({ weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], preload: false, })

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Rizki Siraj</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={`bg-gray-900 min-h-screen px-4 py-6 ${poppins.className}`}>
        <main className="max-w-2xl h-full w-full mx-auto py-4">
          <section className="mb-4">
            <div className="mb-4">
              <Image className="mx-auto mb-2 rounded-full border-4 border-indigo-500" width={150} height={150} src="/avatar.webp" alt="avatar" />
            </div>
            <h1 className="text-white font-semibold text-2xl mb-2 text-center">Rizki Siraj</h1>
            <p className="text-gray-300 font-light text-sm text-center">Mobile Developer | Student of the Universe | Lifelong Learner</p>
          </section>
          <hr />
          <section className="my-4">
            <p className="text-gray-200">Hey guys! Siraj here, and this is my blog. I'm a 3rd year CompSci student, who is very passionate on learning about technology especially on mobile development. I spend most of my time by coding stuffs with {<BrandCard icon={<IconBrandFlutter className="inline-block" size={16} />} name="Flutter" link="flutter.dev" />}, {<BrandCard icon={<IconBrandSwift className="inline-block" size={16} />} name="SwiftUI" link="https://developer.apple.com/xcode/swiftui/" />}, {<BrandCard icon={<IconBrandReact className="inline-block" size={16} />} name="React" link="react.dev" />}. I also made several projects that you can see here :</p>
          </section>
        </main>
      </section>
    </>
  );
}
